### ISSUE TITLE
extra observations in some populations

### ISSUE THREAD

**Issue by carolinapinapaez** [isaacovercast/easySFS#51] opened 2022-10-20 22:59 UTC
Hello, 

I successfully ran easySFS on all of my 7 populations, but 3 out of 7 populations have some extra observations. My vcf file only contains variant sites, so this explanation ([https://github.com/isaacovercast/easySFS/issues/42]) does not fit my data.

 
For population 0 (6 diploid individuals) I got two extra observations:
1 observation
d0_0    d0_1    d0_2    d0_3    d0_4    d0_5    d0_6    d0_7
319024.4974747476 43761.53282828289 25044.09848484852 25650.87121212127 0 0 0 0

For population 1 (14 diploid individuas) I got the correct number of observations:
1 observation
d0_0    d0_1    d0_2    d0_3    d0_4    d0_5    d0_6    d0_7    d0_8    d0_9    d0_10   d0_11   d0_12   d0_13
287568.8188270652 47115.51097463361 23362.86639819917 14844.89689793532 12304.88181627339 13188.7428444833 15095.2822414091 0 0 0 0 0 0 0

For population 0, I have two extra observations, for populations 4 and 6 I have one extra observation/population. I'm wondering why is this happening. 

Here is the command that I ran:

easySFS.py -i 87_NOMISS.vcf.gz -p 87_msia_pops.txt -a --proj=7,13,14,14,11,14,11

Thank you for your help!

**Comment by isaacovercast** [comment] 2022-10-21 20:03
Hello Carolina,

This is the expected behavior, but it might not be obvious why. There are 2 things happening that I see here:

1) It is the selected projection value that determines the number of bins in the final SFS, not the number of diploid samples that are input. If you have 6 diploid samples (12 haploid), and choose the projection value of 7, this will down-project the 12 haploids to a sample size of 7. The same goes for all the other populations, the selected projection value will down-project each population to the selected _haploid_ sample size. So when you say (for population 0) that there are 2 extra observations (sfs bins), this is probably because you are expecting the number of bins to correspond to the diploid sample size (6) and not the projection value (7), which is actually how the sfs will be determined. 

2) In all cases, the 'extra' bin (the 'zero' bin) in the SFS records the # of invariant sites. If you take 6 haploid samples, and project down to a sample size of 7 then you will have one sfs bin for snps at each of the possible frequencies: singletons, doubletons, tripletons, ... and so on, one bin for each of the 7 possible frequency classes, and then the zero bin, which records sites that are monomorphic within your sample. Your vcf file only contains variable sites, but this doesn't mean there _aren't_ sites that are invariable within a given subsample of the individuals. It is also highly probable that the act of projecting down from higher sample sizes will create sites that are invariable in the down-projection that were variable (and low frequency) in the total population. This is expected behavior, it's just an outcome of the down-sampling process.

I'm going to close this issue, but feel free to reach out to me if you have more questions.

Hope that helps!
-isaac

**Closed by isaacovercast** 2022-10-21 20:03 UTC

**Comment by isaacovercast** [comment] 2022-10-26 18:28
+1
